export const DEMOS = [
  {
    id: 1,
    title: 'Portfolio Website',
    description: 'Professional portfolio showcasing projects and experience',
    category: 'Portfolio',
    color: 'from-blue-600 to-blue-800',
  },
  {
    id: 2,
    title: 'Tech Startup',
    description: 'Modern tech company landing page with features',
    category: 'Startup',
    color: 'from-purple-600 to-purple-800',
  },
  {
    id: 3,
    title: 'SaaS Product',
    description: 'Software-as-a-service product marketing site',
    category: 'SaaS',
    color: 'from-cyan-600 to-cyan-800',
  },
  {
    id: 4,
    title: 'Digital Agency',
    description: 'Creative agency showcasing portfolio and services',
    category: 'Agency',
    color: 'from-orange-600 to-orange-800',
  },
  {
    id: 5,
    title: 'E-commerce Store',
    description: 'Online retail platform with product showcase',
    category: 'E-commerce',
    color: 'from-green-600 to-green-800',
  },
  {
    id: 6,
    title: 'Restaurant Website',
    description: 'Food business site with menu and reservations',
    category: 'Food',
    color: 'from-red-600 to-red-800',
  },
  {
    id: 7,
    title: 'Fitness Center',
    description: 'Gym and fitness services with membership info',
    category: 'Health',
    color: 'from-indigo-600 to-indigo-800',
  },
  {
    id: 8,
    title: 'Real Estate',
    description: 'Property listing showcase and agent services',
    category: 'Real Estate',
    color: 'from-amber-600 to-amber-800',
  },
  {
    id: 9,
    title: 'Education Platform',
    description: 'Online learning center with course catalogs',
    category: 'Education',
    color: 'from-emerald-600 to-emerald-800',
  },
  {
    id: 10,
    title: 'Travel Agency',
    description: 'Travel services with package deals and bookings',
    category: 'Travel',
    color: 'from-sky-600 to-sky-800',
  },
  {
    id: 11,
    title: 'Photography Studio',
    description: 'Portfolio and booking site for photographers',
    category: 'Photography',
    color: 'from-slate-600 to-slate-800',
  },
  {
    id: 12,
    title: 'Consulting Firm',
    description: 'Business consulting services and expertise showcase',
    category: 'Consulting',
    color: 'from-zinc-600 to-zinc-800',
  },
  {
    id: 13,
    title: 'Mobile App Landing',
    description: 'App promotion page with download links',
    category: 'Technology',
    color: 'from-fuchsia-600 to-fuchsia-800',
  },
  {
    id: 14,
    title: 'Event Management',
    description: 'Event planning and booking platform',
    category: 'Events',
    color: 'from-rose-600 to-rose-800',
  },
  {
    id: 15,
    title: 'Finance Services',
    description: 'Financial advisory and investment services',
    category: 'Finance',
    color: 'from-lime-600 to-lime-800',
  },
  {
    id: 16,
    title: 'Healthcare Clinic',
    description: 'Medical services and appointment booking',
    category: 'Healthcare',
    color: 'from-teal-600 to-teal-800',
  },
  {
    id: 17,
    title: 'Pet Care Services',
    description: 'Pet grooming and veterinary services',
    category: 'Pet Care',
    color: 'from-pink-600 to-pink-800',
  },
  {
    id: 18,
    title: 'Jewelry Store',
    description: 'Luxury jewelry showcase and online shopping',
    category: 'Retail',
    color: 'from-yellow-600 to-yellow-800',
  },
  {
    id: 19,
    title: 'Legal Services',
    description: 'Law firm website with practice areas',
    category: 'Legal',
    color: 'from-violet-600 to-violet-800',
  },
  {
    id: 20,
    title: 'Automotive Dealership',
    description: 'Car dealership with inventory and financing',
    category: 'Automotive',
    color: 'from-cyan-600 to-cyan-800',
  },
];

export const demoContent = {
  about: 'We are dedicated to providing exceptional services and solutions to our clients worldwide.',
  services: [
    'Professional Service 1',
    'Expert Consultation',
    'Quality Delivery',
    'Customer Support',
  ],
};
